<!-- guide01 — 에셋 HTML 템플릿 (clone용, components 폴더 내 동일 경로 include) -->
<div id="guide01-templates" hidden aria-hidden="true">
  <div data-template="autoship_icon"><!--#include file="autoship_icon.asp"--></div>
  <div data-template="autoship_icon_c"><!--#include file="autoship_icon_c.asp"--></div>
  <div data-template="base_business_icon"><!--#include file="base_business_icon.asp"--></div>
  <div data-template="base_business_icon_c"><!--#include file="base_business_icon_c.asp"--></div>
  <div data-template="recommend_bonus_icon"><!--#include file="recommend_bonus_icon.asp"--></div>
  <div data-template="recommend_bonus_icon_c"><!--#include file="recommend_bonus_icon_c.asp"--></div>
  <div data-template="discount_benefit_icon"><!--#include file="discount_benefit_icon.asp"--></div>
  <div data-template="discount_benefit_icon_c"><!--#include file="discount_benefit_icon_c.asp"--></div>
  <div data-template="discount_benefit_badge"><!--#include file="discount_benefit_badge.asp"--></div>
  <div data-template="discount_benefit_badge_c"><!--#include file="discount_benefit_badge_c.asp"--></div>
  <div data-template="member_icon"><!--#include file="member_icon.asp"--></div>
  <div data-template="person_icon"><!--#include file="person_icon.asp"--></div>
  <div data-template="lev_d"><!--#include file="lev_d.asp"--></div>
  <div data-template="lev_p"><!--#include file="lev_p.asp"--></div>
  <div data-template="calendar_month_card"><!--#include file="calendar_month_card.asp"--></div>
  <div data-template="product_silhouette_card"><!--#include file="product_silhouette_card.asp"--></div>
  <div data-template="unavailable_stamp"><!--#include file="unavailable_stamp.asp"--></div>
  <div data-template="price_step_card"><!--#include file="price_step_card.asp"--></div>
  <div data-template="status_check_icon"><!--#include file="status_check_icon.asp"--></div>
  <div data-template="cashback_icon"><!--#include file="cashback_icon.asp"--></div>
  <div data-template="cashback_icon_c"><!--#include file="cashback_icon_c.asp"--></div>
  <div data-template="effect_plus_icon"><!--#include file="effect_plus_icon.asp"--></div>
  <div data-template="point_token_icon"><!--#include file="point_token_icon.asp"--></div>
  <div data-template="guide_info_badge"><!--#include file="guide_info_badge.asp"--></div>
  <div data-template="auto_renewal_icon"><!--#include file="auto_renewal_icon.asp"--></div>
  <div data-template="subscription_flow_card"><!--#include file="subscription_flow_card.asp"--></div>
  <div data-template="autoship_discount_summary_card"><!--#include file="autoship_discount_summary_card.asp"--></div>
  <div data-template="reward_plan_basis_box"><!--#include file="reward_plan_basis_box.asp"--></div>
  <div data-template="member_basis_card"><!--#include file="member_basis_card.asp"--></div>
  <div data-template="group_bracket"><!--#include file="group_bracket.asp"--></div>
  <div data-template="product_swap_box"><!--#include file="product_swap_box.asp"--></div>
  <div data-template="product_swap_icon"><!--#include file="product_swap_icon.asp"--></div>
  <div data-template="cancel_request_card"><!--#include file="cancel_request_card.asp"--></div>
  <div data-template="payment_stop_icon"><!--#include file="payment_stop_icon.asp"--></div>
  <div data-template="business_flow_card"><!--#include file="business_flow_card.asp"--></div>
  <div data-template="subscription_system_frame"><!--#include file="subscription_system_frame.asp"--></div>
  <div data-template="cursor_click_icon"><!--#include file="cursor_click_icon.asp"--></div>
  <div data-template="payment_batch_box"><!--#include file="payment_batch_box.asp"--></div>
  <div data-template="delivery_batch_box"><!--#include file="delivery_batch_box.asp"--></div>
  <div data-template="installment_mini_badge"><!--#include file="installment_mini_badge.asp"--></div>
  <div data-template="quarter_renew_summary"><!--#include file="quarter_renew_summary.asp"--></div>
  <div data-template="subscription_renew_payment_box"><!--#include file="subscription_renew_payment_box.asp"--></div>
  <div data-template="delivery_box_icon"><!--#include file="delivery_box_icon.asp"--></div>
  <div data-template="payment_card_icon"><!--#include file="payment_card_icon.asp"--></div>
</div>
